# Generated by Django 4.2.6 on 2023-12-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_topup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappNums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
