# Generated by Django 4.2.6 on 2023-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_notificationstatus_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
