# Generated by Django 4.2.6 on 2023-12-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='order',
            field=models.CharField(max_length=6),
        ),
    ]
