# Generated by Django 4.2.6 on 2023-12-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_alter_payments_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
