# Generated by Django 4.0.6 on 2023-12-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_order_prepared'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
