# Generated by Django 4.2.6 on 2024-01-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_payments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
    ]
