# Generated by Django 4.2.6 on 2024-01-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='number',
            field=models.CharField(default=666, max_length=8),
            preserve_default=False,
        ),
    ]
