# Generated by Django 4.2.6 on 2024-01-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_feedback_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='number',
        ),
    ]
