# Generated by Django 4.2.6 on 2024-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_alter_customuser_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='university',
            field=models.CharField(default='Sabanci', max_length=20, blank=True, null=True),
        ),
    ]
