# Generated by Django 5.0.2 on 2024-03-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_pasta_alter_customuser_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamadanSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CSimage', models.ImageField(upload_to='ramadan_images/')),
            ],
        ),
    ]
